version: '3.8'

services:
  # Frontend (Angular)
  frontend:
    build: ./frontend
    ports:
      - "4200:80"  # Map host port 4200 to container port 80
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8080/api  # Backend API URL

  # Backend (Spring Boot with Gradle)
  backend:
    build: ./backend
    ports:
      - "8080:8080"  # Map host port 8080 to container port 8080
    depends_on:
      - oracle-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521/XE
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: Oracle123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update  # Automatically update the database schema
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Oracle Database
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    environment:
      ORACLE_PWD: Oracle123  # Default password for the SYS and SYSTEM users
    ports:
      - "1521:1521"  # Map host port 1521 to container port 1521
    volumes:
      - oracle-data:/opt/oracle/oradata  # Persist Oracle data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql  # Initialize the database
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'SELECT 1 FROM DUAL;' | sqlplus system/Oracle123@localhost:1521/XE"]
      interval: 30s
      timeout: 10s
      retries: 5

# Volumes for persistent data
volumes:
  oracle-data:
